name: Experiments SNAX

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  accfg-experiments-snax:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    container: 
      image: ghcr.io/kuleuven-micas/snax:v0.1.6    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install snax-mlir
        working-directory: snax-mlir
        run: python3 -m pip install -r requirements.txt -e .
      - name: Run accfg benchmarks
        working-directory: snax-mlir/kernels/streamer_matmul
        run: python3 genbenchmark.py
      - name: Install postprocessing requirements
        run: pip install -e .
      - name: Run postprocessing
        run: python3 get_all_numbers.py ../snax-mlir/kernels/streamer_matmul/results -o results.pkl
        working-directory: accfg_artifacts
      - name: Create plot bar chart
        run: python3 plot_snax.py --plot=bar_plot -i results.pkl -o bar_chart.png
        working-directory: accfg_artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: bar_chart 
          path: bar_chart.png 
      - name: Create plot roofline chart
        run: python3 plot_snax.py --plot=roofline -i results.pkl -o roofline_chart.png
        working-directory: accfg_artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: roofline
          path: roofline_chart.png 
